# Generated by Django 5.2.8 on 2026-03-12 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日期')),
                ('content', models.TextField(verbose_name='计划内容')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL, verbose_name='组员')),
            ],
            options={
                'verbose_name': '日常计划',
                'verbose_name_plural': '日常计划',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_topic', models.CharField(max_length=120, verbose_name='研究课题')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='组员')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
    ]
