# Generated by Django 5.2.8 on 2026-03-12 13:25

import django.db.models.deletion
import lab_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='填写头像图片的URL地址', verbose_name='头像链接'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_post_announcement',
            field=models.BooleanField(default=False, verbose_name='可发布公告'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_page',
            field=models.URLField(blank=True, help_text='个人博客、GitHub等', verbose_name='个人主页链接'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('file', models.FileField(upload_to=lab_management.models.user_directory_path, verbose_name='文件')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('txt', '文本'), ('excel', 'Excel'), ('other', '其他')], max_length=20, verbose_name='文档类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
