# Generated by Django 5.2.8 on 2026-03-13 01:26

import lab_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0002_userprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, help_text='上传本地头像图片（支持 JPG、PNG 格式）', null=True, upload_to=lab_management.models.avatar_directory_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_page',
            field=models.URLField(blank=True, help_text='个人博客、GitHub 等', verbose_name='个人主页链接'),
        ),
    ]
