# Generated by Django 5.2.8 on 2026-03-13 01:29

import lab_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0003_remove_userprofile_avatar_url_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='上传本地头像图片', null=True, upload_to=lab_management.models.avatar_directory_path, verbose_name='头像'),
        ),
    ]
