# Generated by Django 5.2.8 on 2026-03-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True, help_text='公开文档可被所有人查看，不公开仅自己可见', verbose_name='公开'),
        ),
    ]
