# Generated by Django 5.2.8 on 2026-03-13 03:32

import django.db.models.deletion
import lab_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0005_document_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='成果名称')),
                ('achievement_type', models.CharField(choices=[('paper', '论文'), ('patent', '专利'), ('award', '奖项'), ('project', '项目'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to=lab_management.models.user_directory_path, verbose_name='附件')),
                ('link', models.URLField(blank=True, help_text='论文链接、专利链接等', verbose_name='链接')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '成果',
                'verbose_name_plural': '成果',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
