# Generated by Django 5.2.8 on 2026-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='用于联系的邮箱地址', max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='用于联系的电话号码', max_length=20, verbose_name='联系电话'),
        ),
    ]
