# Generated by Django 6.0.3 on 2026-03-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0009_announcement_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplan',
            options={'ordering': ['date', 'order', '-id'], 'verbose_name': '日常计划', 'verbose_name_plural': '日常计划'},
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_plans', to='lab_management.dailyplan', verbose_name='主计划'),
        ),
    ]
