# Generated by Django 6.0.3 on 2026-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0010_alter_dailyplan_options_dailyplan_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='公开计划可被所有人查看，不公开仅自己可见', verbose_name='公开'),
        ),
    ]
