# Generated by Django 6.0.3 on 2026-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0011_dailyplan_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='comments_enabled',
            field=models.BooleanField(default=True, help_text='关闭后用户无法评论', verbose_name='开启评论'),
        ),
    ]
