# Generated by Django 5.2.12 on 2026-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0013_announcementcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[('1', '一年级'), ('2', '二年级'), ('3', '三年级')], default='1', help_text='选择年级（硕士适用）', max_length=5, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_type',
            field=models.CharField(choices=[('master', '硕士'), ('phd', '博士')], default='master', help_text='选择硕士或博士', max_length=10, verbose_name='成员类型'),
        ),
    ]
