# Generated by Django 6.0.3 on 2026-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0014_alter_announcement_options_userprofile_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='member_type',
            field=models.CharField(choices=[('phd', '博士研究生'), ('master', '硕士研究生'), ('undergraduate', '本科生'), ('graduated', '已毕业')], default='master', help_text='选择成员类型', max_length=20, verbose_name='成员类型'),
        ),
    ]
