# Generated by Django 6.0.3 on 2026-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0015_expand_member_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('project', '项目文档'), ('paper', '论文资料'), ('experiment', '实验数据'), ('learning', '学习资料'), ('meeting', '会议资料')], default='project', max_length=20, verbose_name='文档分类'),
        ),
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载次数'),
        ),
    ]
