# Generated by Django 6.0.3 on 2026-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0017_resume_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('system', '系统公告'), ('academic', '学术通知'), ('team', '团队动态'), ('important', '重要通知')], default='system', max_length=20, verbose_name='公告类型'),
        ),
    ]
