# Generated by Django 5.2.12 on 2026-05-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0018_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='deadline',
            field=models.DateField(blank=True, help_text='不设置表示至今', null=True, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='is_delayed',
            field=models.BooleanField(default=False, verbose_name='是否延期'),
        ),
    ]
