from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('members/', views.member_list, name='member_list'),
    path('plans/', views.plan_list, name='plan_list'),
    path('overview/', views.team_overview, name='team_overview'),
    path('documents/', views.document_list, name='document_list'),
    path('announcements/', views.announcement_list, name='announcement_list'),
    path('user/<str:username>/', views.user_profile, name='user_profile'),
    path('my/', views.my_page, name='my_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add/document/', views.add_document, name='add_document'),
    path('download/document/<int:doc_id>/', views.download_document, name='download_document'),
    path('preview/document/<int:doc_id>/', views.preview_document, name='preview_document'),
    path('delete/document/<int:doc_id>/', views.delete_document, name='delete_document'),
    path('add/plan/', views.add_plan, name='add_plan'),
    path('edit/plan/<int:plan_id>/', views.edit_plan, name='edit_plan'),
    path('delete/plan/<int:plan_id>/', views.delete_plan, name='delete_plan'),
    path('toggle/plan/<int:plan_id>/', views.toggle_plan, name='toggle_plan'),
    path('api/subplan/add/', views.add_sub_plan_ajax, name='add_sub_plan_ajax'),
    path('add/announcement/', views.add_announcement, name='add_announcement'),
    path('edit/announcement/<int:ann_id>/', views.edit_announcement, name='edit_announcement'),
    path('delete/announcement/<int:ann_id>/', views.delete_announcement, name='delete_announcement'),
    path('announcement/<int:ann_id>/comment/', views.add_announcement_comment, name='add_announcement_comment'),
    path('announcement/comment/<int:comment_id>/delete/', views.delete_announcement_comment, name='delete_announcement_comment'),
    path('edit/profile/', views.edit_profile, name='edit_profile'),
    path('add/achievement/', views.add_achievement, name='add_achievement'),
    path('delete/achievement/<int:ach_id>/', views.delete_achievement, name='delete_achievement'),
    path('send_message/<str:username>/', views.send_message, name='send_message'),
    path('delete_message/<int:msg_id>/', views.delete_message, name='delete_message'),
    path('delete/user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('ai/chat/', views.ai_chat, name='ai_chat'),
    path('search/', views.search, name='search'),
    path('export/', views.export_data, name='export_data'),
    path('resume/', views.resume_builder, name='resume_builder'),
]
